name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matejuk/city-traffic-simulator-backend:latest
          context: './city-traffic-simulator-backend'
          file: './city-traffic-simulator-backend/Dockerfile'
  update-VPS-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update image inside VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -q --filter ancestor=matejuk/city-traffic-simulator-backend )
            docker pull matejuk/city-traffic-simulator-backend
            docker run -d -p 3001:3001 matejuk/city-traffic-simulator-backend
